config/routes.rb
Rails.application.routes.draw do
  resources :resources
  resources :activities
  resources :actions
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get 'rcpsp_start'=> 'static_pages#rcpsp_start'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :overtime_cost %><br>
    <%= f.text_field :overtime_cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table id="resources" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Kapazität</th>
      <th>Überstundenkosten</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.capacity %></td>
        <td><%= resource.overtime_cost %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neue Ressource', new_resource_path %>
<br>  <br><%= link_to 'Zurück zur Projektplanung', rcpsp_start_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @resource, :name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @resource.capacity %>
</p>

<p>
  <strong>Overtime cost:</strong>
  <%= @resource.overtime_cost %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>