config/routes.rb
Rails.application.routes.draw do
  resources :resources
  resources :activities
  resources :actions
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get 'rcpsp_start'=> 'static_pages#rcpsp_start'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :resource
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :processing_time, :earliest_end, :latest_end, :resource_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label 'Ressource auswählen' %><br />
      <%= f.collection_select :resource_id, Resource.all, :id, :name %>
    </div>
  <div class="field">
    <%= f.label :processing_time %><br>
    <%= f.number_field :processing_time %>
  </div>
  <div class="field">
    <%= f.label :earliest_end %><br>
    <%= f.number_field :earliest_end %>
  </div>
  <div class="field">
    <%= f.label :latest_end %><br>
    <%= f.number_field :latest_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table id="activities" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Vorgangsdauer</th>
      <th>Ressource</th>
      <th>Frühestes Ende</th>
      <th>Spätestes Ende</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.processing_time %></td>
        <td><%= activity.resource.name %></td>
        <td><%= activity.earliest_end %></td>
        <td><%= activity.latest_end %></td>
        <td><%= link_to 'Anzeigen', activity %></td>
        <td><%= link_to 'Bearbeiten', edit_activity_path(activity) %></td>
        <td><%= link_to 'Löschen', activity, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neuer Vorgang', new_activity_path %>
<br>  <br><%= link_to 'Zurück zur Projektplanung', rcpsp_start_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @activity, :name %>
</p>

<p>
  <strong>Processing time:</strong>
  <%= @activity.processing_time %>
</p>

<p>
  <b>Ressource:</b>
  <%= @activity.resource.name %>
</p>
<p>
  <strong>Earliest end:</strong>
  <%= @activity.earliest_end %>
</p>

<p>
  <strong>Latest end:</strong>
  <%= @activity.latest_end %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>